### ISSUE TITLE
TypeError: Cannot read property '__checkoutUI' of undefined at init

### ISSUE THREAD

**Issue by jirkaa** [Adyen/adyen-web-sdk-sample-code#12] opened 2018-05-22 09:21 UTC
I have a problem with calling $.ajax in beforeComplete hook.

I cloned this repository, set credentials in authentication.ini and ran the project. Everything goes OK except beforeComplete hook. I see a form with credit card  fields, I am able to fill it and send it. 
In beforeComplete hook in `paymentData` variable are `resultCode:"authorised"`  and `resultText:"Payment Successful"`. 

But line with calling $.ajax causes this error (catched on line 1313 in "unminifed" version): 
```
TypeError: Cannot read property '__checkoutUI' of undefined
    at init (https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSDK.1.2.3.js:5251:52)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7727)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7608)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Ab (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7631)
    at Function.r.param (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:7918)
```

**Comment by sponglord** [comment] 2018-05-24 13:05
Hi jirkaa,
Can you please show us what your chckt.hooks.beforeComplete function looks like?

**Comment by jirkaa** [comment] 2018-05-28 10:26
Hi sponglord, 
my chckt.hooks.beforeComplete function is exactly same as you can see in file [index.php](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/a9112f238eed64386be3b24b1dd911227fe0a33a/index.php#L76) in this repository. I didn't change it. 

I made `git clone git@github.com:Adyen/adyen-web-sdk-sample-code.git`, added file `config/authentication.ini` and run. No other change.

**Comment by pabloai** [comment] 2018-06-06 09:52
Hi @jirkaa 

Thanks for sharing this.
We were able to reproduce it and will be fixed in next release.

For now you can make a temporary fix by adding the next line in [index.php:77](https://github.com/Adyen/adyen-web-sdk-sample-code/blob/a9112f238eed64386be3b24b1dd911227fe0a33a/index.php#L77)

```js
delete paymentData.selectedPMNode;
```

Regards,

Pablo

**Comment by Trigalti** [comment] 2018-11-05 12:36
Resolved

**Closed by Trigalti** 2018-11-05 12:36 UTC
